version: "3.9"

services:
  web:
    build: .
    container_name: wastedetection_app
    command: gunicorn wastedetection.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
